services:
  docs:
    image: new_shop_local_docs
    container_name: new_shop_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./new_shop:/app/new_shop:z
    ports:
      - '9000:9000'
    command: /start-docs
