# Generated by Django 4.2.13 on 2024-05-15 14:39

import common.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_role'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', common.manager.CustomUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Not chosen'), (1, 'Male'), (2, 'Female')], default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='Phone Number'),
        ),
    ]
