# Generated by Django 4.2.13 on 2024-05-16 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Male'), (2, 'Female')], default=1),
        ),
    ]
